### ISSUE TITLE
Review del desafío 🕵🏼 

### ISSUE THREAD

**Issue by tobiasfacello** [marcelaborgarello/desafio-m5#1]
Buenas noches Marce querida, felicidades por haber terminado el desafío del módulo 🚀 
No tengo mucho para comentar a nivel técnico, la verdad que anda todo espectacular y se ve que cuidaste mucho lo que respecta a la interacción del usuario para con la app. Sinceramente me encantó.
Sin más para comentar como bien decía al principio, felicidades nuevamente y éxitos en el próximo módulo!

**Comment by marcelaborgarello** [comment]
> Buenas noches Marce querida, felicidades por haber terminado el desafío del módulo rocket No tengo mucho para comentar a nivel técnico, la verdad que anda todo espectacular y se ve que cuidaste mucho lo que respecta a la interacción del usuario para con la app. Sinceramente me encantó. Sin más para comentar como bien decía al principio, felicidades nuevamente y éxitos en el próximo módulo!

Muchas gracias por tu tiempo y tu issue. Es alentador. :)
